# fly.toml app configuration file generated for nrf-metaobject-webhooks on 2023-12-13T03:05:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nrf-metaobject-webhooks"
primary_region = "ord"

[build]

[env]
  DATABASE_URL = "file:/data/sqlite.db"

[mounts]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
